language: node_js
node_js:
  - '8'
  - '10'
  - '12'
branches:
  only:
    - master
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn install --frozen-lockfile --ignore-engines
script:
  - yarn run build
  - yarn run lint
  - scripts/test-ci.sh
