language: node_js
node_js:
  - '10'
env:
  - COMMAND=build
  - COMMAND=test:ci
  - COMMAND=lint
branches:
  only:
    - master
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn --frozen-lockfile
script:
  - yarn run $COMMAND
