language: node_js
node_js:
  - '10'
branches:
  only:
    - master
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn --frozen-lockfile
script:
  - yarn run build
  - yarn run lint
  - yarn run test:ci
